// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CmdMsg.proto

package com.bbstone.comm.proto;

public final class CmdMsg {
  private CmdMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CmdReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bbstone.comm.proto.CmdReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string cmd = 2;</code>
     * @return The cmd.
     */
    java.lang.String getCmd();
    /**
     * <code>string cmd = 2;</code>
     * @return The bytes for cmd.
     */
    com.google.protobuf.ByteString
        getCmdBytes();

    /**
     * <code>string data = 3;</code>
     * @return The data.
     */
    java.lang.String getData();
    /**
     * <code>string data = 3;</code>
     * @return The bytes for data.
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <code>string connId = 4;</code>
     * @return The connId.
     */
    java.lang.String getConnId();
    /**
     * <code>string connId = 4;</code>
     * @return The bytes for connId.
     */
    com.google.protobuf.ByteString
        getConnIdBytes();

    /**
     * <code>uint64 reqTs = 5;</code>
     * @return The reqTs.
     */
    long getReqTs();

    /**
     * <code>string accessToken = 6;</code>
     * @return The accessToken.
     */
    java.lang.String getAccessToken();
    /**
     * <code>string accessToken = 6;</code>
     * @return The bytes for accessToken.
     */
    com.google.protobuf.ByteString
        getAccessTokenBytes();

    /**
     * <code>uint64 createTs = 7;</code>
     * @return The createTs.
     */
    long getCreateTs();
  }
  /**
   * Protobuf type {@code com.bbstone.comm.proto.CmdReq}
   */
  public static final class CmdReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bbstone.comm.proto.CmdReq)
      CmdReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CmdReq.newBuilder() to construct.
    private CmdReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CmdReq() {
      id_ = "";
      cmd_ = "";
      data_ = "";
      connId_ = "";
      accessToken_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CmdReq();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CmdReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              cmd_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              connId_ = s;
              break;
            }
            case 40: {

              reqTs_ = input.readUInt64();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              accessToken_ = s;
              break;
            }
            case 56: {

              createTs_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bbstone.comm.proto.CmdMsg.internal_static_com_bbstone_comm_proto_CmdReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bbstone.comm.proto.CmdMsg.internal_static_com_bbstone_comm_proto_CmdReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bbstone.comm.proto.CmdMsg.CmdReq.class, com.bbstone.comm.proto.CmdMsg.CmdReq.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CMD_FIELD_NUMBER = 2;
    private volatile java.lang.Object cmd_;
    /**
     * <code>string cmd = 2;</code>
     * @return The cmd.
     */
    @java.lang.Override
    public java.lang.String getCmd() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cmd_ = s;
        return s;
      }
    }
    /**
     * <code>string cmd = 2;</code>
     * @return The bytes for cmd.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCmdBytes() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private volatile java.lang.Object data_;
    /**
     * <code>string data = 3;</code>
     * @return The data.
     */
    @java.lang.Override
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <code>string data = 3;</code>
     * @return The bytes for data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONNID_FIELD_NUMBER = 4;
    private volatile java.lang.Object connId_;
    /**
     * <code>string connId = 4;</code>
     * @return The connId.
     */
    @java.lang.Override
    public java.lang.String getConnId() {
      java.lang.Object ref = connId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        connId_ = s;
        return s;
      }
    }
    /**
     * <code>string connId = 4;</code>
     * @return The bytes for connId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getConnIdBytes() {
      java.lang.Object ref = connId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        connId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQTS_FIELD_NUMBER = 5;
    private long reqTs_;
    /**
     * <code>uint64 reqTs = 5;</code>
     * @return The reqTs.
     */
    @java.lang.Override
    public long getReqTs() {
      return reqTs_;
    }

    public static final int ACCESSTOKEN_FIELD_NUMBER = 6;
    private volatile java.lang.Object accessToken_;
    /**
     * <code>string accessToken = 6;</code>
     * @return The accessToken.
     */
    @java.lang.Override
    public java.lang.String getAccessToken() {
      java.lang.Object ref = accessToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accessToken_ = s;
        return s;
      }
    }
    /**
     * <code>string accessToken = 6;</code>
     * @return The bytes for accessToken.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccessTokenBytes() {
      java.lang.Object ref = accessToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accessToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATETS_FIELD_NUMBER = 7;
    private long createTs_;
    /**
     * <code>uint64 createTs = 7;</code>
     * @return The createTs.
     */
    @java.lang.Override
    public long getCreateTs() {
      return createTs_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getCmdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cmd_);
      }
      if (!getDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, data_);
      }
      if (!getConnIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, connId_);
      }
      if (reqTs_ != 0L) {
        output.writeUInt64(5, reqTs_);
      }
      if (!getAccessTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, accessToken_);
      }
      if (createTs_ != 0L) {
        output.writeUInt64(7, createTs_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getCmdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cmd_);
      }
      if (!getDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, data_);
      }
      if (!getConnIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, connId_);
      }
      if (reqTs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, reqTs_);
      }
      if (!getAccessTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, accessToken_);
      }
      if (createTs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, createTs_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bbstone.comm.proto.CmdMsg.CmdReq)) {
        return super.equals(obj);
      }
      com.bbstone.comm.proto.CmdMsg.CmdReq other = (com.bbstone.comm.proto.CmdMsg.CmdReq) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getCmd()
          .equals(other.getCmd())) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!getConnId()
          .equals(other.getConnId())) return false;
      if (getReqTs()
          != other.getReqTs()) return false;
      if (!getAccessToken()
          .equals(other.getAccessToken())) return false;
      if (getCreateTs()
          != other.getCreateTs()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + getCmd().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + CONNID_FIELD_NUMBER;
      hash = (53 * hash) + getConnId().hashCode();
      hash = (37 * hash) + REQTS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getReqTs());
      hash = (37 * hash) + ACCESSTOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getAccessToken().hashCode();
      hash = (37 * hash) + CREATETS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateTs());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bbstone.comm.proto.CmdMsg.CmdReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bbstone.comm.proto.CmdMsg.CmdReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bbstone.comm.proto.CmdMsg.CmdReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bbstone.comm.proto.CmdMsg.CmdReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bbstone.comm.proto.CmdMsg.CmdReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bbstone.comm.proto.CmdMsg.CmdReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bbstone.comm.proto.CmdMsg.CmdReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bbstone.comm.proto.CmdMsg.CmdReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bbstone.comm.proto.CmdMsg.CmdReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bbstone.comm.proto.CmdMsg.CmdReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bbstone.comm.proto.CmdMsg.CmdReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bbstone.comm.proto.CmdMsg.CmdReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bbstone.comm.proto.CmdMsg.CmdReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bbstone.comm.proto.CmdReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bbstone.comm.proto.CmdReq)
        com.bbstone.comm.proto.CmdMsg.CmdReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bbstone.comm.proto.CmdMsg.internal_static_com_bbstone_comm_proto_CmdReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bbstone.comm.proto.CmdMsg.internal_static_com_bbstone_comm_proto_CmdReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bbstone.comm.proto.CmdMsg.CmdReq.class, com.bbstone.comm.proto.CmdMsg.CmdReq.Builder.class);
      }

      // Construct using com.bbstone.comm.proto.CmdMsg.CmdReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        cmd_ = "";

        data_ = "";

        connId_ = "";

        reqTs_ = 0L;

        accessToken_ = "";

        createTs_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bbstone.comm.proto.CmdMsg.internal_static_com_bbstone_comm_proto_CmdReq_descriptor;
      }

      @java.lang.Override
      public com.bbstone.comm.proto.CmdMsg.CmdReq getDefaultInstanceForType() {
        return com.bbstone.comm.proto.CmdMsg.CmdReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.bbstone.comm.proto.CmdMsg.CmdReq build() {
        com.bbstone.comm.proto.CmdMsg.CmdReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bbstone.comm.proto.CmdMsg.CmdReq buildPartial() {
        com.bbstone.comm.proto.CmdMsg.CmdReq result = new com.bbstone.comm.proto.CmdMsg.CmdReq(this);
        result.id_ = id_;
        result.cmd_ = cmd_;
        result.data_ = data_;
        result.connId_ = connId_;
        result.reqTs_ = reqTs_;
        result.accessToken_ = accessToken_;
        result.createTs_ = createTs_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bbstone.comm.proto.CmdMsg.CmdReq) {
          return mergeFrom((com.bbstone.comm.proto.CmdMsg.CmdReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bbstone.comm.proto.CmdMsg.CmdReq other) {
        if (other == com.bbstone.comm.proto.CmdMsg.CmdReq.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getCmd().isEmpty()) {
          cmd_ = other.cmd_;
          onChanged();
        }
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        if (!other.getConnId().isEmpty()) {
          connId_ = other.connId_;
          onChanged();
        }
        if (other.getReqTs() != 0L) {
          setReqTs(other.getReqTs());
        }
        if (!other.getAccessToken().isEmpty()) {
          accessToken_ = other.accessToken_;
          onChanged();
        }
        if (other.getCreateTs() != 0L) {
          setCreateTs(other.getCreateTs());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bbstone.comm.proto.CmdMsg.CmdReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bbstone.comm.proto.CmdMsg.CmdReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cmd_ = "";
      /**
       * <code>string cmd = 2;</code>
       * @return The cmd.
       */
      public java.lang.String getCmd() {
        java.lang.Object ref = cmd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cmd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cmd = 2;</code>
       * @return The bytes for cmd.
       */
      public com.google.protobuf.ByteString
          getCmdBytes() {
        java.lang.Object ref = cmd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cmd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cmd = 2;</code>
       * @param value The cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cmd = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmd() {
        
        cmd_ = getDefaultInstance().getCmd();
        onChanged();
        return this;
      }
      /**
       * <code>string cmd = 2;</code>
       * @param value The bytes for cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cmd_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <code>string data = 3;</code>
       * @return The data.
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string data = 3;</code>
       * @return The bytes for data.
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string data = 3;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string data = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>string data = 3;</code>
       * @param value The bytes for data to set.
       * @return This builder for chaining.
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object connId_ = "";
      /**
       * <code>string connId = 4;</code>
       * @return The connId.
       */
      public java.lang.String getConnId() {
        java.lang.Object ref = connId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          connId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string connId = 4;</code>
       * @return The bytes for connId.
       */
      public com.google.protobuf.ByteString
          getConnIdBytes() {
        java.lang.Object ref = connId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          connId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string connId = 4;</code>
       * @param value The connId to set.
       * @return This builder for chaining.
       */
      public Builder setConnId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        connId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string connId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearConnId() {
        
        connId_ = getDefaultInstance().getConnId();
        onChanged();
        return this;
      }
      /**
       * <code>string connId = 4;</code>
       * @param value The bytes for connId to set.
       * @return This builder for chaining.
       */
      public Builder setConnIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        connId_ = value;
        onChanged();
        return this;
      }

      private long reqTs_ ;
      /**
       * <code>uint64 reqTs = 5;</code>
       * @return The reqTs.
       */
      @java.lang.Override
      public long getReqTs() {
        return reqTs_;
      }
      /**
       * <code>uint64 reqTs = 5;</code>
       * @param value The reqTs to set.
       * @return This builder for chaining.
       */
      public Builder setReqTs(long value) {
        
        reqTs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 reqTs = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearReqTs() {
        
        reqTs_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object accessToken_ = "";
      /**
       * <code>string accessToken = 6;</code>
       * @return The accessToken.
       */
      public java.lang.String getAccessToken() {
        java.lang.Object ref = accessToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          accessToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string accessToken = 6;</code>
       * @return The bytes for accessToken.
       */
      public com.google.protobuf.ByteString
          getAccessTokenBytes() {
        java.lang.Object ref = accessToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accessToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string accessToken = 6;</code>
       * @param value The accessToken to set.
       * @return This builder for chaining.
       */
      public Builder setAccessToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        accessToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string accessToken = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccessToken() {
        
        accessToken_ = getDefaultInstance().getAccessToken();
        onChanged();
        return this;
      }
      /**
       * <code>string accessToken = 6;</code>
       * @param value The bytes for accessToken to set.
       * @return This builder for chaining.
       */
      public Builder setAccessTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        accessToken_ = value;
        onChanged();
        return this;
      }

      private long createTs_ ;
      /**
       * <code>uint64 createTs = 7;</code>
       * @return The createTs.
       */
      @java.lang.Override
      public long getCreateTs() {
        return createTs_;
      }
      /**
       * <code>uint64 createTs = 7;</code>
       * @param value The createTs to set.
       * @return This builder for chaining.
       */
      public Builder setCreateTs(long value) {
        
        createTs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 createTs = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreateTs() {
        
        createTs_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bbstone.comm.proto.CmdReq)
    }

    // @@protoc_insertion_point(class_scope:com.bbstone.comm.proto.CmdReq)
    private static final com.bbstone.comm.proto.CmdMsg.CmdReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bbstone.comm.proto.CmdMsg.CmdReq();
    }

    public static com.bbstone.comm.proto.CmdMsg.CmdReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CmdReq>
        PARSER = new com.google.protobuf.AbstractParser<CmdReq>() {
      @java.lang.Override
      public CmdReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CmdReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CmdReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CmdReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bbstone.comm.proto.CmdMsg.CmdReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CmdRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bbstone.comm.proto.CmdRsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string cmd = 2;</code>
     * @return The cmd.
     */
    java.lang.String getCmd();
    /**
     * <code>string cmd = 2;</code>
     * @return The bytes for cmd.
     */
    com.google.protobuf.ByteString
        getCmdBytes();

    /**
     * <code>int32 retCode = 3;</code>
     * @return The retCode.
     */
    int getRetCode();

    /**
     * <code>string retMsg = 4;</code>
     * @return The retMsg.
     */
    java.lang.String getRetMsg();
    /**
     * <code>string retMsg = 4;</code>
     * @return The bytes for retMsg.
     */
    com.google.protobuf.ByteString
        getRetMsgBytes();

    /**
     * <code>string retData = 5;</code>
     * @return The retData.
     */
    java.lang.String getRetData();
    /**
     * <code>string retData = 5;</code>
     * @return The bytes for retData.
     */
    com.google.protobuf.ByteString
        getRetDataBytes();

    /**
     * <code>uint64 reqTs = 6;</code>
     * @return The reqTs.
     */
    long getReqTs();

    /**
     * <code>uint64 recvTs = 7;</code>
     * @return The recvTs.
     */
    long getRecvTs();

    /**
     * <code>uint64 rspTs = 8;</code>
     * @return The rspTs.
     */
    long getRspTs();

    /**
     * <code>string connId = 9;</code>
     * @return The connId.
     */
    java.lang.String getConnId();
    /**
     * <code>string connId = 9;</code>
     * @return The bytes for connId.
     */
    com.google.protobuf.ByteString
        getConnIdBytes();

    /**
     * <code>string accessToken = 10;</code>
     * @return The accessToken.
     */
    java.lang.String getAccessToken();
    /**
     * <code>string accessToken = 10;</code>
     * @return The bytes for accessToken.
     */
    com.google.protobuf.ByteString
        getAccessTokenBytes();

    /**
     * <code>uint64 createTs = 11;</code>
     * @return The createTs.
     */
    long getCreateTs();
  }
  /**
   * Protobuf type {@code com.bbstone.comm.proto.CmdRsp}
   */
  public static final class CmdRsp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bbstone.comm.proto.CmdRsp)
      CmdRspOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CmdRsp.newBuilder() to construct.
    private CmdRsp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CmdRsp() {
      id_ = "";
      cmd_ = "";
      retMsg_ = "";
      retData_ = "";
      connId_ = "";
      accessToken_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CmdRsp();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CmdRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              cmd_ = s;
              break;
            }
            case 24: {

              retCode_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              retMsg_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              retData_ = s;
              break;
            }
            case 48: {

              reqTs_ = input.readUInt64();
              break;
            }
            case 56: {

              recvTs_ = input.readUInt64();
              break;
            }
            case 64: {

              rspTs_ = input.readUInt64();
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              connId_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              accessToken_ = s;
              break;
            }
            case 88: {

              createTs_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bbstone.comm.proto.CmdMsg.internal_static_com_bbstone_comm_proto_CmdRsp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bbstone.comm.proto.CmdMsg.internal_static_com_bbstone_comm_proto_CmdRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bbstone.comm.proto.CmdMsg.CmdRsp.class, com.bbstone.comm.proto.CmdMsg.CmdRsp.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CMD_FIELD_NUMBER = 2;
    private volatile java.lang.Object cmd_;
    /**
     * <code>string cmd = 2;</code>
     * @return The cmd.
     */
    @java.lang.Override
    public java.lang.String getCmd() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cmd_ = s;
        return s;
      }
    }
    /**
     * <code>string cmd = 2;</code>
     * @return The bytes for cmd.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCmdBytes() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RETCODE_FIELD_NUMBER = 3;
    private int retCode_;
    /**
     * <code>int32 retCode = 3;</code>
     * @return The retCode.
     */
    @java.lang.Override
    public int getRetCode() {
      return retCode_;
    }

    public static final int RETMSG_FIELD_NUMBER = 4;
    private volatile java.lang.Object retMsg_;
    /**
     * <code>string retMsg = 4;</code>
     * @return The retMsg.
     */
    @java.lang.Override
    public java.lang.String getRetMsg() {
      java.lang.Object ref = retMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        retMsg_ = s;
        return s;
      }
    }
    /**
     * <code>string retMsg = 4;</code>
     * @return The bytes for retMsg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRetMsgBytes() {
      java.lang.Object ref = retMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        retMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RETDATA_FIELD_NUMBER = 5;
    private volatile java.lang.Object retData_;
    /**
     * <code>string retData = 5;</code>
     * @return The retData.
     */
    @java.lang.Override
    public java.lang.String getRetData() {
      java.lang.Object ref = retData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        retData_ = s;
        return s;
      }
    }
    /**
     * <code>string retData = 5;</code>
     * @return The bytes for retData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRetDataBytes() {
      java.lang.Object ref = retData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        retData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQTS_FIELD_NUMBER = 6;
    private long reqTs_;
    /**
     * <code>uint64 reqTs = 6;</code>
     * @return The reqTs.
     */
    @java.lang.Override
    public long getReqTs() {
      return reqTs_;
    }

    public static final int RECVTS_FIELD_NUMBER = 7;
    private long recvTs_;
    /**
     * <code>uint64 recvTs = 7;</code>
     * @return The recvTs.
     */
    @java.lang.Override
    public long getRecvTs() {
      return recvTs_;
    }

    public static final int RSPTS_FIELD_NUMBER = 8;
    private long rspTs_;
    /**
     * <code>uint64 rspTs = 8;</code>
     * @return The rspTs.
     */
    @java.lang.Override
    public long getRspTs() {
      return rspTs_;
    }

    public static final int CONNID_FIELD_NUMBER = 9;
    private volatile java.lang.Object connId_;
    /**
     * <code>string connId = 9;</code>
     * @return The connId.
     */
    @java.lang.Override
    public java.lang.String getConnId() {
      java.lang.Object ref = connId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        connId_ = s;
        return s;
      }
    }
    /**
     * <code>string connId = 9;</code>
     * @return The bytes for connId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getConnIdBytes() {
      java.lang.Object ref = connId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        connId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCESSTOKEN_FIELD_NUMBER = 10;
    private volatile java.lang.Object accessToken_;
    /**
     * <code>string accessToken = 10;</code>
     * @return The accessToken.
     */
    @java.lang.Override
    public java.lang.String getAccessToken() {
      java.lang.Object ref = accessToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accessToken_ = s;
        return s;
      }
    }
    /**
     * <code>string accessToken = 10;</code>
     * @return The bytes for accessToken.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccessTokenBytes() {
      java.lang.Object ref = accessToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accessToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATETS_FIELD_NUMBER = 11;
    private long createTs_;
    /**
     * <code>uint64 createTs = 11;</code>
     * @return The createTs.
     */
    @java.lang.Override
    public long getCreateTs() {
      return createTs_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getCmdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cmd_);
      }
      if (retCode_ != 0) {
        output.writeInt32(3, retCode_);
      }
      if (!getRetMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, retMsg_);
      }
      if (!getRetDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, retData_);
      }
      if (reqTs_ != 0L) {
        output.writeUInt64(6, reqTs_);
      }
      if (recvTs_ != 0L) {
        output.writeUInt64(7, recvTs_);
      }
      if (rspTs_ != 0L) {
        output.writeUInt64(8, rspTs_);
      }
      if (!getConnIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, connId_);
      }
      if (!getAccessTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, accessToken_);
      }
      if (createTs_ != 0L) {
        output.writeUInt64(11, createTs_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getCmdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cmd_);
      }
      if (retCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, retCode_);
      }
      if (!getRetMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, retMsg_);
      }
      if (!getRetDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, retData_);
      }
      if (reqTs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, reqTs_);
      }
      if (recvTs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, recvTs_);
      }
      if (rspTs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(8, rspTs_);
      }
      if (!getConnIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, connId_);
      }
      if (!getAccessTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, accessToken_);
      }
      if (createTs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(11, createTs_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bbstone.comm.proto.CmdMsg.CmdRsp)) {
        return super.equals(obj);
      }
      com.bbstone.comm.proto.CmdMsg.CmdRsp other = (com.bbstone.comm.proto.CmdMsg.CmdRsp) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getCmd()
          .equals(other.getCmd())) return false;
      if (getRetCode()
          != other.getRetCode()) return false;
      if (!getRetMsg()
          .equals(other.getRetMsg())) return false;
      if (!getRetData()
          .equals(other.getRetData())) return false;
      if (getReqTs()
          != other.getReqTs()) return false;
      if (getRecvTs()
          != other.getRecvTs()) return false;
      if (getRspTs()
          != other.getRspTs()) return false;
      if (!getConnId()
          .equals(other.getConnId())) return false;
      if (!getAccessToken()
          .equals(other.getAccessToken())) return false;
      if (getCreateTs()
          != other.getCreateTs()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + getCmd().hashCode();
      hash = (37 * hash) + RETCODE_FIELD_NUMBER;
      hash = (53 * hash) + getRetCode();
      hash = (37 * hash) + RETMSG_FIELD_NUMBER;
      hash = (53 * hash) + getRetMsg().hashCode();
      hash = (37 * hash) + RETDATA_FIELD_NUMBER;
      hash = (53 * hash) + getRetData().hashCode();
      hash = (37 * hash) + REQTS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getReqTs());
      hash = (37 * hash) + RECVTS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRecvTs());
      hash = (37 * hash) + RSPTS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRspTs());
      hash = (37 * hash) + CONNID_FIELD_NUMBER;
      hash = (53 * hash) + getConnId().hashCode();
      hash = (37 * hash) + ACCESSTOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getAccessToken().hashCode();
      hash = (37 * hash) + CREATETS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateTs());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bbstone.comm.proto.CmdMsg.CmdRsp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bbstone.comm.proto.CmdMsg.CmdRsp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bbstone.comm.proto.CmdMsg.CmdRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bbstone.comm.proto.CmdMsg.CmdRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bbstone.comm.proto.CmdMsg.CmdRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bbstone.comm.proto.CmdMsg.CmdRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bbstone.comm.proto.CmdMsg.CmdRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bbstone.comm.proto.CmdMsg.CmdRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bbstone.comm.proto.CmdMsg.CmdRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bbstone.comm.proto.CmdMsg.CmdRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bbstone.comm.proto.CmdMsg.CmdRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bbstone.comm.proto.CmdMsg.CmdRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bbstone.comm.proto.CmdMsg.CmdRsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bbstone.comm.proto.CmdRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bbstone.comm.proto.CmdRsp)
        com.bbstone.comm.proto.CmdMsg.CmdRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bbstone.comm.proto.CmdMsg.internal_static_com_bbstone_comm_proto_CmdRsp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bbstone.comm.proto.CmdMsg.internal_static_com_bbstone_comm_proto_CmdRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bbstone.comm.proto.CmdMsg.CmdRsp.class, com.bbstone.comm.proto.CmdMsg.CmdRsp.Builder.class);
      }

      // Construct using com.bbstone.comm.proto.CmdMsg.CmdRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        cmd_ = "";

        retCode_ = 0;

        retMsg_ = "";

        retData_ = "";

        reqTs_ = 0L;

        recvTs_ = 0L;

        rspTs_ = 0L;

        connId_ = "";

        accessToken_ = "";

        createTs_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bbstone.comm.proto.CmdMsg.internal_static_com_bbstone_comm_proto_CmdRsp_descriptor;
      }

      @java.lang.Override
      public com.bbstone.comm.proto.CmdMsg.CmdRsp getDefaultInstanceForType() {
        return com.bbstone.comm.proto.CmdMsg.CmdRsp.getDefaultInstance();
      }

      @java.lang.Override
      public com.bbstone.comm.proto.CmdMsg.CmdRsp build() {
        com.bbstone.comm.proto.CmdMsg.CmdRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bbstone.comm.proto.CmdMsg.CmdRsp buildPartial() {
        com.bbstone.comm.proto.CmdMsg.CmdRsp result = new com.bbstone.comm.proto.CmdMsg.CmdRsp(this);
        result.id_ = id_;
        result.cmd_ = cmd_;
        result.retCode_ = retCode_;
        result.retMsg_ = retMsg_;
        result.retData_ = retData_;
        result.reqTs_ = reqTs_;
        result.recvTs_ = recvTs_;
        result.rspTs_ = rspTs_;
        result.connId_ = connId_;
        result.accessToken_ = accessToken_;
        result.createTs_ = createTs_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bbstone.comm.proto.CmdMsg.CmdRsp) {
          return mergeFrom((com.bbstone.comm.proto.CmdMsg.CmdRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bbstone.comm.proto.CmdMsg.CmdRsp other) {
        if (other == com.bbstone.comm.proto.CmdMsg.CmdRsp.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getCmd().isEmpty()) {
          cmd_ = other.cmd_;
          onChanged();
        }
        if (other.getRetCode() != 0) {
          setRetCode(other.getRetCode());
        }
        if (!other.getRetMsg().isEmpty()) {
          retMsg_ = other.retMsg_;
          onChanged();
        }
        if (!other.getRetData().isEmpty()) {
          retData_ = other.retData_;
          onChanged();
        }
        if (other.getReqTs() != 0L) {
          setReqTs(other.getReqTs());
        }
        if (other.getRecvTs() != 0L) {
          setRecvTs(other.getRecvTs());
        }
        if (other.getRspTs() != 0L) {
          setRspTs(other.getRspTs());
        }
        if (!other.getConnId().isEmpty()) {
          connId_ = other.connId_;
          onChanged();
        }
        if (!other.getAccessToken().isEmpty()) {
          accessToken_ = other.accessToken_;
          onChanged();
        }
        if (other.getCreateTs() != 0L) {
          setCreateTs(other.getCreateTs());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bbstone.comm.proto.CmdMsg.CmdRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bbstone.comm.proto.CmdMsg.CmdRsp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cmd_ = "";
      /**
       * <code>string cmd = 2;</code>
       * @return The cmd.
       */
      public java.lang.String getCmd() {
        java.lang.Object ref = cmd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cmd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cmd = 2;</code>
       * @return The bytes for cmd.
       */
      public com.google.protobuf.ByteString
          getCmdBytes() {
        java.lang.Object ref = cmd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cmd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cmd = 2;</code>
       * @param value The cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cmd = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmd() {
        
        cmd_ = getDefaultInstance().getCmd();
        onChanged();
        return this;
      }
      /**
       * <code>string cmd = 2;</code>
       * @param value The bytes for cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cmd_ = value;
        onChanged();
        return this;
      }

      private int retCode_ ;
      /**
       * <code>int32 retCode = 3;</code>
       * @return The retCode.
       */
      @java.lang.Override
      public int getRetCode() {
        return retCode_;
      }
      /**
       * <code>int32 retCode = 3;</code>
       * @param value The retCode to set.
       * @return This builder for chaining.
       */
      public Builder setRetCode(int value) {
        
        retCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 retCode = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRetCode() {
        
        retCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object retMsg_ = "";
      /**
       * <code>string retMsg = 4;</code>
       * @return The retMsg.
       */
      public java.lang.String getRetMsg() {
        java.lang.Object ref = retMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          retMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string retMsg = 4;</code>
       * @return The bytes for retMsg.
       */
      public com.google.protobuf.ByteString
          getRetMsgBytes() {
        java.lang.Object ref = retMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          retMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string retMsg = 4;</code>
       * @param value The retMsg to set.
       * @return This builder for chaining.
       */
      public Builder setRetMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        retMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string retMsg = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearRetMsg() {
        
        retMsg_ = getDefaultInstance().getRetMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string retMsg = 4;</code>
       * @param value The bytes for retMsg to set.
       * @return This builder for chaining.
       */
      public Builder setRetMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        retMsg_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object retData_ = "";
      /**
       * <code>string retData = 5;</code>
       * @return The retData.
       */
      public java.lang.String getRetData() {
        java.lang.Object ref = retData_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          retData_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string retData = 5;</code>
       * @return The bytes for retData.
       */
      public com.google.protobuf.ByteString
          getRetDataBytes() {
        java.lang.Object ref = retData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          retData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string retData = 5;</code>
       * @param value The retData to set.
       * @return This builder for chaining.
       */
      public Builder setRetData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        retData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string retData = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearRetData() {
        
        retData_ = getDefaultInstance().getRetData();
        onChanged();
        return this;
      }
      /**
       * <code>string retData = 5;</code>
       * @param value The bytes for retData to set.
       * @return This builder for chaining.
       */
      public Builder setRetDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        retData_ = value;
        onChanged();
        return this;
      }

      private long reqTs_ ;
      /**
       * <code>uint64 reqTs = 6;</code>
       * @return The reqTs.
       */
      @java.lang.Override
      public long getReqTs() {
        return reqTs_;
      }
      /**
       * <code>uint64 reqTs = 6;</code>
       * @param value The reqTs to set.
       * @return This builder for chaining.
       */
      public Builder setReqTs(long value) {
        
        reqTs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 reqTs = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearReqTs() {
        
        reqTs_ = 0L;
        onChanged();
        return this;
      }

      private long recvTs_ ;
      /**
       * <code>uint64 recvTs = 7;</code>
       * @return The recvTs.
       */
      @java.lang.Override
      public long getRecvTs() {
        return recvTs_;
      }
      /**
       * <code>uint64 recvTs = 7;</code>
       * @param value The recvTs to set.
       * @return This builder for chaining.
       */
      public Builder setRecvTs(long value) {
        
        recvTs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 recvTs = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearRecvTs() {
        
        recvTs_ = 0L;
        onChanged();
        return this;
      }

      private long rspTs_ ;
      /**
       * <code>uint64 rspTs = 8;</code>
       * @return The rspTs.
       */
      @java.lang.Override
      public long getRspTs() {
        return rspTs_;
      }
      /**
       * <code>uint64 rspTs = 8;</code>
       * @param value The rspTs to set.
       * @return This builder for chaining.
       */
      public Builder setRspTs(long value) {
        
        rspTs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 rspTs = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearRspTs() {
        
        rspTs_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object connId_ = "";
      /**
       * <code>string connId = 9;</code>
       * @return The connId.
       */
      public java.lang.String getConnId() {
        java.lang.Object ref = connId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          connId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string connId = 9;</code>
       * @return The bytes for connId.
       */
      public com.google.protobuf.ByteString
          getConnIdBytes() {
        java.lang.Object ref = connId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          connId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string connId = 9;</code>
       * @param value The connId to set.
       * @return This builder for chaining.
       */
      public Builder setConnId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        connId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string connId = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearConnId() {
        
        connId_ = getDefaultInstance().getConnId();
        onChanged();
        return this;
      }
      /**
       * <code>string connId = 9;</code>
       * @param value The bytes for connId to set.
       * @return This builder for chaining.
       */
      public Builder setConnIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        connId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object accessToken_ = "";
      /**
       * <code>string accessToken = 10;</code>
       * @return The accessToken.
       */
      public java.lang.String getAccessToken() {
        java.lang.Object ref = accessToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          accessToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string accessToken = 10;</code>
       * @return The bytes for accessToken.
       */
      public com.google.protobuf.ByteString
          getAccessTokenBytes() {
        java.lang.Object ref = accessToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accessToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string accessToken = 10;</code>
       * @param value The accessToken to set.
       * @return This builder for chaining.
       */
      public Builder setAccessToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        accessToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string accessToken = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccessToken() {
        
        accessToken_ = getDefaultInstance().getAccessToken();
        onChanged();
        return this;
      }
      /**
       * <code>string accessToken = 10;</code>
       * @param value The bytes for accessToken to set.
       * @return This builder for chaining.
       */
      public Builder setAccessTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        accessToken_ = value;
        onChanged();
        return this;
      }

      private long createTs_ ;
      /**
       * <code>uint64 createTs = 11;</code>
       * @return The createTs.
       */
      @java.lang.Override
      public long getCreateTs() {
        return createTs_;
      }
      /**
       * <code>uint64 createTs = 11;</code>
       * @param value The createTs to set.
       * @return This builder for chaining.
       */
      public Builder setCreateTs(long value) {
        
        createTs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 createTs = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreateTs() {
        
        createTs_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bbstone.comm.proto.CmdRsp)
    }

    // @@protoc_insertion_point(class_scope:com.bbstone.comm.proto.CmdRsp)
    private static final com.bbstone.comm.proto.CmdMsg.CmdRsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bbstone.comm.proto.CmdMsg.CmdRsp();
    }

    public static com.bbstone.comm.proto.CmdMsg.CmdRsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CmdRsp>
        PARSER = new com.google.protobuf.AbstractParser<CmdRsp>() {
      @java.lang.Override
      public CmdRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CmdRsp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CmdRsp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CmdRsp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bbstone.comm.proto.CmdMsg.CmdRsp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bbstone_comm_proto_CmdReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bbstone_comm_proto_CmdReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bbstone_comm_proto_CmdRsp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bbstone_comm_proto_CmdRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014CmdMsg.proto\022\026com.bbstone.comm.proto\"u" +
      "\n\006CmdReq\022\n\n\002id\030\001 \001(\t\022\013\n\003cmd\030\002 \001(\t\022\014\n\004dat" +
      "a\030\003 \001(\t\022\016\n\006connId\030\004 \001(\t\022\r\n\005reqTs\030\005 \001(\004\022\023" +
      "\n\013accessToken\030\006 \001(\t\022\020\n\010createTs\030\007 \001(\004\"\270\001" +
      "\n\006CmdRsp\022\n\n\002id\030\001 \001(\t\022\013\n\003cmd\030\002 \001(\t\022\017\n\007ret" +
      "Code\030\003 \001(\005\022\016\n\006retMsg\030\004 \001(\t\022\017\n\007retData\030\005 " +
      "\001(\t\022\r\n\005reqTs\030\006 \001(\004\022\016\n\006recvTs\030\007 \001(\004\022\r\n\005rs" +
      "pTs\030\010 \001(\004\022\016\n\006connId\030\t \001(\t\022\023\n\013accessToken" +
      "\030\n \001(\t\022\020\n\010createTs\030\013 \001(\004B\"\n\026com.bbstone." +
      "comm.protoB\006CmdMsgH\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_bbstone_comm_proto_CmdReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bbstone_comm_proto_CmdReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bbstone_comm_proto_CmdReq_descriptor,
        new java.lang.String[] { "Id", "Cmd", "Data", "ConnId", "ReqTs", "AccessToken", "CreateTs", });
    internal_static_com_bbstone_comm_proto_CmdRsp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_bbstone_comm_proto_CmdRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bbstone_comm_proto_CmdRsp_descriptor,
        new java.lang.String[] { "Id", "Cmd", "RetCode", "RetMsg", "RetData", "ReqTs", "RecvTs", "RspTs", "ConnId", "AccessToken", "CreateTs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
